[project]
name = "wmos-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cx-oracle>=8.3.0",
    "dotenv>=0.9.9",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
